### ISSUE TITLE
Integrate TCP Brutal with this script

### ISSUE THREAD

**Issue by xenstar** [yonggekkk/sing-box#20]
Hello Brother. Thank you for creating YouTube videos for us. Very helpful.

Can you integrate https://github.com/apernet/tcp-brutal with this script?

I wanted to try this script. Thank you.

And do you have any plan to integrate the hysterical protocol with you x-ui script. Because to use this sing-box-yg script have to again install it in another server.

**Comment by yonggekkk** [comment]
> Hello Brother. Thank you for creating YouTube videos for us. Very helpful.
> 
> Can you integrate https://github.com/apernet/tcp-brutal with this script?
> 
> I wanted to try this script. Thank you.
> 
> And do you have any plan to integrate the hysterical protocol with you x-ui script. Because to use this sing-box-yg script have to again install it in another server.

Tcp-brutal is an additional option that needs to be installed separately. It must support multiplexing and has requirements for the vps kernel version. It also needs to set the upload and download values. For ordinary users, it is not a necessary choice. The default bbr is very stable.
XUI itself only has an XRAY kernel, and adding hysteria requires reconstruction, which is unrealistic.
