### ISSUE TITLE
侃哥你好，安装报错

### ISSUE THREAD

**Issue by Gingtin** [yonggekkk/sing-box#22]
提示parse error: ':' not as part of an object at line 67, column 29 应该怎么处理?

**Comment by yonggekkk** [comment]
> 提示parse error: ':' not as part of an object at line 67, column 29 应该怎么处理?

这是导入客户端的报错？？？还是？

**Comment by Gingtin** [comment]
不是  安装sing-box时最后一步报错

Sing-box安装成功，脚本快捷方式为 sb
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29

**Comment by Gingtin** [comment]
Sing-box状态：未启动，可选择6重启，依旧如此选择10查看日志并反馈，建议卸载重装Sing-box
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
Sing-box节点关键信息、已分流域名情况如下：
parse error: ':' not as part of an object at line 67, column 29
🚀【 Vless-reality 】端口:  SNI域名证书:
🚀【 Vmess-ws-tls  】端口:   证书形式:TLS开启   Argo状态:不支持开启
🚀【  Hysteria-2   】端口:  证书形式:域名证书  转发多端口: ,,,,,,,,match,,,,,,,,,,
🚀【    Tuic-v5    】端口:  证书形式:域名证书  转发多端口: ,,,,,,,,match,,,,,,,,,,

**Comment by Gingtin** [comment]
日志：
● sing-box.service
     Loaded: loaded (/etc/systemd/system/sing-box.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-12-04 18:49:04 MST; 4s ago
    Process: 83514 ExecStart=/etc/s-box/sing-box run -c /etc/s-box/sb.json (code=exited, status=1/FAILURE)
   Main PID: 83514 (code=exited, status=1/FAILURE)
        CPU: 10ms

**Comment by yonggekkk** [comment]
> parse error: ':' not as part of an object at line 67, column 29

什么VPS。什么系统，点卸载重装下

**Comment by Gingtin** [comment]
VPS系统信息如下：
 操作系统: Debian GNU/Linux 11 (bullseye)  内核版本: 5.10.0  CPU架构 : arm64  虚拟化类型: kvm
好奇怪  安装依赖的过程里，没有发现有其他的报错

**Comment by Gingtin** [comment]
Vless-reality相关key与id将自动生成……
sysctl: setting key "net.ipv4.icmp_echo_ignore_all": Invalid argument
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
五、针对vmess-ws协议，加入Cloudflared-Argo临时隧道功能
parse error: ':' not as part of an object at line 67, column 29
parse error: ':' not as part of an object at line 67, column 29
因vmess开启了tls，Argo隧道功能不可用


是不是这哪里出现了啥问题

**Comment by yonggekkk** [comment]
> VPS系统信息如下： 操作系统: Debian GNU/Linux 11 (bullseye) 内核版本: 5.10.0 CPU架构 : arm64 虚拟化类型: kvm 好奇怪 安装依赖的过程里，没有发现有其他的报错

你这是甲骨文DD吗？

**Comment by Gingtin** [comment]
对  是的

**Comment by yonggekkk** [comment]
> 对 是的

别DD了，用原装ubuntu 22.04吧
