### ISSUE TITLE
Singbox file for Nekobox

### ISSUE THREAD

**Issue by SalarAbapour** [yonggekkk/sing-box#23]
Please also prepare a file for Nekobox. Thank you

**Comment by yonggekkk** [comment]
There are already shared links and QR codes

**Comment by SalarAbapour** [comment]
The ing_box_client.json  is not working in nekobox. Please make a file for nekobox too. Thank you sir.

**Comment by yonggekkk** [comment]
> The sing_box_client.json is not working in nekobox. Please make a file for nekobox too. Thank you sir.


Nekobox is a client with built-in sing box configuration. And sing_box_client.json applies to SFI, SFA, and SFW clients.

**Comment by SalarAbapour** [comment]
Please look at this file: https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/singbox/sfasfi/mix.json
This file behavior like your sing_box_client.json but in Nekobox. Can you make a file like this in your project folder?

**Comment by yonggekkk** [comment]
> Please look at this file: https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/singbox/sfasfi/mix.json This file behavior like your sing_box_client.json but in Nekobox. Can you make a file like this in your project folder?

It adds the characteristic parameters consistent with nekobox. .

**Comment by SalarAbapour** [comment]
Can I please you add a file like this but of your proxies?

**Comment by yonggekkk** [comment]
Not for the moment

**Comment by SalarAbapour** [comment]
Singbox client is not working in some models of phones in Iran. But nekobox is OK. Thank you.
